# Generated by Django 5.1.7 on 2025-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='database_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
