# Generated by Django 5.1.7 on 2025-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_databaseconnection_database_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('puerto', models.IntegerField()),
                ('dbname', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DatabaseConnection',
        ),
    ]
