# Generated by Django 5.1.7 on 2025-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sqlexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='info_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
