# Generated by Django 5.1.7 on 2025-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conexion_info_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
