# Generated by Django 5.1.7 on 2025-03-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_puerto_conexion_port_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conexion',
            old_name='contrasena',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='conexion',
            old_name='nombre',
            new_name='password',
        ),
    ]
