# Generated by Django 5.1.7 on 2025-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_contrasena_conexion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='db_type',
            field=models.CharField(default='mysql', max_length=255),
            preserve_default=False,
        ),
    ]
