# Generated by Django 5.1.7 on 2025-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dangerousquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Database', max_length=100)),
                ('script', models.TextField()),
            ],
        ),
    ]
