# Generated by Django 5.1.7 on 2025-03-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
